### ISSUE TITLE
Clarify different debian / source versions

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/MetaStudent#12]
As discussed today, there may be two different debian packages (one in wheezy and one in ubuntu?) and both of these may be different from the source code.
- [x] Ascertain the existence of different versions
- [x] If applicable, try to identify the version number for each one (search in commits or tags, ...)
- [x] Get version of the debian package I used (stable)
- [x] What is your debian package then? Not stable? jeesy ?
- [x] Please, succinctly document the 3 versions on a wiki page
- [x] Document in the wiki pages, which versions of the data are used (#10)

**Comment by anapetrovska** [comment]
@jmcejuela There are definitely two different debian packages. I ran the installation only with "sudo apt-get install metastudent" and the results are completely different than yours. I guess that is because you refer to different repo "deb http://rostlab.org/debian/ stable main contrib non-free".

![usr-share-screenshot](https://cloud.githubusercontent.com/assets/14331716/12768408/b8f26b32-ca0f-11e5-81eb-d0e30c17f25e.PNG)

And also after this installation there is no metastudent-data-3 existing. This is the screenshot of metastudentrc.default. 

![metastudentrc default-screenshot](https://cloud.githubusercontent.com/assets/14331716/12768476/277be86c-ca10-11e5-907a-44cc71f19ce5.PNG)

**Comment by anapetrovska** [comment]
@jmcejuela And also I took a look at the version. In /usr/lib/python2.7/dist-packages/metastudentPkg directory there is version.py where you can find the version - VERSION = '1.0.11' in our case.

**Comment by anapetrovska** [comment]
In our github source repo we are at the version 2.0.1. which have additional feature. Please refer to ChangeLog file in the source repo.

**Comment by juanmirocks** [comment]
That is great to know. Please briefly review the pending subtasks in the description and document the results on the wiki

**Comment by anapetrovska** [comment]
I got the same output as you (it requires metastudent-data-3).

![capture2](https://cloud.githubusercontent.com/assets/14331716/12802688/f25f0710-cae4-11e5-842e-46939cfb4ad4.PNG)

Unfortunately I cannot find the version of this debian package. The metastudentPkg folder where previously I found the version, now is empty.

![capture3](https://cloud.githubusercontent.com/assets/14331716/12802691/f6cc37dc-cae4-11e5-80ff-a41fdf1f8fe2.PNG)

**Comment by anapetrovska** [comment]
I will close the issue this Thursday. Sorry for being late, but I have very important exam until then.

**Comment by juanmirocks** [comment]
:+1:

**Comment by juanmirocks** [comment]
Good enough :+1: -- thank you so much.

This concludes all pending work for this project
